### ISSUE TITLE
Sometimes, color of linear brush is not correctly encoded

### ISSUE THREAD

**Issue by sehilyi** [gosling-lang/gosling.js#116]

**Comment by ngehlenborg** [comment]
Example of when it goes wrong: https://gosling.js.org/?gist=ngehlenborg/a69476ad02b1bf3caa8d44af7616246b

<img width="617" alt="image" src="https://user-images.githubusercontent.com/1216518/109422427-75ef8f00-79a9-11eb-9be6-89e2189f498d.png">

@sehilyi Do you have an example in which it works?
@flekschas Do you have any insight into what it would take to fix that in HiGlass? 

This would be good to address as soon as possible since it spoils our efforts to make it easy to transition between linear and circular layouts.

**Comment by sehilyi** [comment]
@ngehlenborg I currently use HiGlass' `viewport-projection-horizontal` to show brushes in linear layouts, and testing with `viewport-projection-center` looks to work properly with fill and stroke colors. I would need to look into the code differences between `viewport-projection-horizontal` and `viewport-projection-center` in the HiGlass core.

**Comment by sehilyi** [comment]
I think I found the problem: `viewport-projection-horizontal` does not initialize the brush style in the `constructor()`. I will make a PR in `higlass/higlass` to fix this.


https://github.com/higlass/higlass/pull/1013
