### ISSUE TITLE
refactor visibility condition

### ISSUE THREAD

**Issue by wangqianwen0418** [gosling-lang/gosling.js#124]
Do you think the triggerCondition interface can be refactored in the following way:

```javascript
interface TriggerCondition {
  operation: LogicalOperation,
  measure: "width"|"height"|"zoomLevel",
  threshold: number|"|xe-x|",
  target: 'track' | 'mark' | 'superpose',
  conditionPadding?:number,
  transitionPadding?:number
}
```

this interface looks more clear to me.  
But I totally understand that you might have other design considerations

_Originally posted by @wangqianwen0418 in https://github.com/gosling-lang/gosling.js/discussions/24#discussioncomment-308676_

**Comment by sehilyi** [comment]
I like the renaming "condition" => "measure" & "threshold" which I think is more understandable. I also like the idea to force users to select a single `measure`.

One thing we could additionally do would be separating the interface based on the `measure` since its values (`width`, `height`, `zoomLevel`) use different properties. So something like:

```js
...
visibility?: VisibilityCondition;
...

type VisibilityCondition = SizeVisibilityConsition | ZoomLevelVisibilityCondition;

interface CommonVisibilityCondition {
  operation: LogicalOperation;
  target: 'track' | 'mark'
}

interface SizeVisibilityCondition extends CommonVisibilityCondition {
  measure: 'width' | 'height';
  threshold: number | '|xe-x|;
  conditionPadding?: number;
  transitionPadding?: number;
}

interface ZoomLevelVisibilityCondition extends CommonVisibilityCondition {
  measure: 'zoomLevel';
  threshold: number;
}
```

It would be helpful if you can help on this.

**Comment by wangqianwen0418** [comment]
_Originally posted by @sehilyi in https://github.com/gosling-lang/gosling.js/discussions/24#discussioncomment-308863_

I like the renaming "condition" => "measure" & "threshold" which I think is more understandable. I also like the idea to force users to select a single `measure`.

One thing we could additionally do would be separating the interface based on the `measure` since its values (`width`, `height`, `zoomLevel`) use different properties. So something like:

```js
...
visibility?: VisibilityCondition;
...

type VisibilityCondition = SizeVisibilityConsition | ZoomLevelVisibilityCondition;

interface CommonVisibilityCondition {
  operation: LogicalOperation;
  target: 'track' | 'mark'
}

interface SizeVisibilityCondition extends CommonVisibilityCondition {
  measure: 'width' | 'height';
  threshold: number | '|xe-x|;
  conditionPadding?: number;
  transitionPadding?: number;
}

interface ZoomLevelVisibilityCondition extends CommonVisibilityCondition {
  measure: 'zoomLevel';
  threshold: number;
}
```

**Comment by sehilyi** [comment]
Originally posted by @sehilyi in [#24 (reply in thread)](https://github.com/gosling-lang/gosling.js/discussions/24#discussioncomment-308863)

I like the renaming "condition" => "measure" & "threshold" which I think is more understandable. I also like the idea to force users to select a single measure.

One thing we could additionally do would be separating the interface based on the measure since its values (width, height, zoomLevel) use different properties. So something like:

```js
...
visibility?: VisibilityCondition;
...

type VisibilityCondition = SizeVisibilityConsition | ZoomLevelVisibilityCondition;

interface CommonVisibilityCondition {
  operation: LogicalOperation;
  target: 'track' | 'mark'
}

interface SizeVisibilityCondition extends CommonVisibilityCondition {
  measure: 'width' | 'height';
  threshold: number | '|xe-x|;
  conditionPadding?: number;
  transitionPadding?: number;
}

interface ZoomLevelVisibilityCondition extends CommonVisibilityCondition {
  measure: 'zoomLevel';
  threshold: number;
}
```
