### ISSUE TITLE
Refactor data configuration

### ISSUE THREAD

**Issue by wangqianwen0418** [gosling-lang/gosling.js#161]
@sehilyi , I am looking at the data interface and wondering your opinion about the following refactoring

``` javascript
interface BasicSingleTrack extends CommonTrackDef {
    data: DataDeep;
    ....
}


interface DataDeep {
    dataSource: DataSource
    dataConfig: DataConfig
}

interface DataSource {
    type: "json"|"csv"|"vector"|"bed"|"multivec",
    url: string 
}

interface DataConfig = JSONDataConfig | CSV DataConfig | VectorDataConfig | MultivecDataConfig | BEDDataConfig;

interface JSONDataConfig {
    values: Datum[] 
}

interface CSVDataConfig {
    separator?: string;
    headerNames?: string[];
    chromosomePrefix?: string;
    longToWideId?: string;
}

interface BEDDataConfig {
    genomicFields: { index: number; name: string }[];
    valueFields?: { index: number; name: string; type: 'nominal' | 'quantitative' }[];
    exonIntervalFields?: [{ index: number; name: string }, { index: number; name: string }];
}

interface MultivecDataConfig {
    column: string;
    row: string;
    value: string;
    categories?: string[];
    start?: string;
    end?: string;
    bin?: number;
}

interface VectorDataConfig {
    column: string;
    value: string;
    start?: string;
    end?: string;
    bin?: number; 
}


```

**Comment by wangqianwen0418** [comment]
This is mainly based on two concerns: 
- I am not sure whether the term "metadata" is easy to understand;
- the current structure looks fine when I read the code, but a little bit difficult if I try to explain them in the docs

You are definitely more experienced in the whole code structure. Please let me know your opinion

**Comment by sehilyi** [comment]
Thank you for opening this issue. I was thinking about combining `data` and `metadata` (#95) for the similar reasons but did not had a chance to work on that. (We had a separate `metadata` previously just in case we want to remove that in our spec, but now it is a part of our grammar.).

I like your refactoring suggestion, and one thing I want to suggest is to put all properties inside the `DataDeep` interface rather than having two properties (`dataSource` and `dataConfig`) below it.

```ts
type DataDeep = JSONDataConfig | CSVDataConfig | ...;
interface CSVDataConfig {
    type: "json" | "csv" | "vector" | "bed" | "multivec";
    url: string;
    separator?: string;
    headerNames?: string[];
    chromosomePrefix?: string;
    longToWideId?: string;
}
...
```

In general, I try to avoid adding additional levels of nesting structure for the readability, and I think those two properties can be placed together without making any confusion.

**Comment by wangqianwen0418** [comment]
> In general, I try to avoid adding additional levels of nesting structure for the readability, and I think those two properties can be placed together without making any confusion.

I am considering from the documentation perspective. The data config part significantly varies among different data.
But yes, I see your point and agree with that.
Let's refactor it in the way you suggested.
I will make a pull request later.
