### ISSUE TITLE
Support custom chromsizes

### ISSUE THREAD

**Issue by zhangzhen** [gosling-lang/gosling.js#582]
Adding a custom-defined genome is easy for higlass, while doing this is hard for gosling. Could you please guide me in modifying the source code for gosling to achieve this? After finishing the modification, zooming, panning and zoom_to are expected to function correctly.
Besides, sequence abstraction can be easily implemented by add a custom-defined genome to gosling.

**Comment by sehilyi** [comment]
Hi Zhang! I assume you want to use custom chromosome names and their sizes.

We have a collection of assemblies in [/src/core/utils/assembly.ts](https://github.com/gosling-lang/gosling.js/blob/master/src/core/utils/assembly.ts), so we will need to extend this.

This information is used in several places, for example, in the [axis track](https://github.com/gosling-lang/gosling.js/blob/3cd57a6a499de6a79f5f4bc71947fdb8a44fbdd9/src/gosling-genomic-axis/axis-track.ts#L110).

Grammar-wise, I think a user would need to specify a URL of a TSV file that contains chromosome names and sizes (just like `"chromInfoPath` in HiGlass), e.g., 

```js
// https://github.com/gosling-lang/gosling.js/blob/3cd57a6a499de6a79f5f4bc71947fdb8a44fbdd9/src/core/gosling.schema.ts#L84
assembly: { url: "//s3.amazonaws.com/pkerp/data/hg19/chromSizes.tsv" }
```

I wonder if we can allow users to specify the chr size array directly from the spec (e.g., `{ name: string, length: number}[]`), but this might not be feasible at the moment since HiGlass uses the URL of a TSV file and does not support the inline JSON object in its view config.

**Comment by manzt** [comment]
Came across this recently. There seem to generally be inconsistencies between data-sources and genome assemblies. For example, vcf is hard-coded as `assembly = 'hg38'`, but also hard-coded with chromsizes url for `hg19`?

https://github.com/gosling-lang/gosling.js/blob/a12d454fa9272a03ce76a6cb8cc513ed9ed8d694/src/data-fetcher/vcf/gosling-vcf-data.ts#L30-L42

> I wonder if we can allow users to specify the chr size array directly from the spec (e.g., `{ name: string, length: number}[]`), but this might not be feasible at the moment since HiGlass uses the URL of a TSV file and does not support the inline JSON object in its view config.

You can always create data URLs on the client...

```javascript
let chromsizes = [
  ["foo", 1000],
  ["bar", 300],
  ["baz", 240]
];
let tsv = chromsizes.map((pair) => pair.join("\t")).join("\n");
let url = URL.createObjectURL(new Blob([tsv], { type: "text/tsv" }));
fetch(url).then((res) => res.text()); // `foo\t1000\nbar\t300\nbaz\t240`
```

**Comment by sehilyi** [comment]
>  vcf is hard-coded as assembly = 'hg38', but also hard-coded with chromsizes url for hg19?

Oh man, that should be fixed.

> You can always create data URLs on the client...

Didn't know this! I think this can be incorporated when passing the assembly URLs when constructing HiGlass viewconfig:

https://github.com/gosling-lang/gosling.js/blob/a12d454fa9272a03ce76a6cb8cc513ed9ed8d694/src/core/higlass-model.ts#L84

**Comment by manzt** [comment]
It's important to note that Gosling is totally limited to (a set) of human/mouse genome visualization without this feature.

Something to think about: since we have exposed "assembly" as a field for datasets, adding an additional "chromsizes" field would allow for configurations which are not correct. 

```
{
 ...
 "assembly": "hg38",
 "chromsizes": [ ["foo", 1000], ["bar", 300], ["baz", 240]]
}
```

### Option 1: extend `Assembly` with a literal for chromsizes (preferred)

```typescript
type ChromSizes = [name: string, length: number][];
export type Assembly = 'hg38' | 'hg19' | 'hg18' | 'hg17' | 'hg16' | 'mm10' | 'mm9' | 'unknown' |  ChromSizes;
```

This seems like it could be the most simple to implement and likely least confusing to end users.

### Option 2: enforce either "assembly" or "chromsizes" at the type-level

"chromsizes" doesn't need to be a full assembly, so `chromsizes` seems like a more appropriate naming (like was chosen in higlass) to allow users to define how to layout chromosomes on a genomic axis. We could allow users to set `assembly` out of convenience (as is currently implemented), but if a user had custom genome they could specify `chromsizes`. We could make the fields mutually exclusive at the type-level.

### Top-level definition

Regardless of the approach taken, we could implement something very similar to #508 to allow custom genomes to be referenced:

```json
{
  "assemblies": {
    "myAssembly": [["foo", 1000], ["bar", 300], ["baz", 240]],
  },
  "datasets": {
    "myDataset": {
      "type": "vcf", 
      "url": "https://example.com/data.vcf.bz",
      "indexUrl": "https://example.com/data.vcf.bz.tbi",
      "assembly": "myAssembly",
    }
  },
 "tracks": { ... }
}
```

**Comment by sehilyi** [comment]
I like both. I would prefer the first option since the second one adds a bit of complexity to the grammar to users and the naming of the first option looks acceptable to me.

Just one clarification is that we let users specify assembly at the view level (i.e., all tracks that belong to the same view use the same assembly).

I pinned this issue since this is important to address.

**Comment by manzt** [comment]
> I like both. I would prefer the first option since the second one adds a bit of complexity to the grammar to users and the naming of the first option looks acceptable to me.
 
 Sounds good to me! (I changed my preferences in the previous comment because I think the simplicity outweighs the "correctness" of assembly vs chromsizes naming)

>  Just one clarification is that we let users specify assembly at the view level (i.e., all tracks that belong to the same view use the same assembly).

Ah that makes sense. I guess assembly can be like a "dataset" which is referenced for the View.


> I pinned this issue since this is important to address.

Agreed!
