### ISSUE TITLE
Support diverse aggregation functions, such as `sum` and `mean`, for HiGlass files (e.g., `vector`)

### ISSUE THREAD

**Issue by zhangzhen** [gosling-lang/gosling.js#587]
Calculating average over tileUnitSize should be removed when the data type is vector because higlass has done the calculation once somehow.  Doing it twice causes the y-axis domain to show incorrect values.
The changes I've made to the code is shown in the following figure.

![image](https://user-images.githubusercontent.com/782824/142818413-970f433f-0524-401f-a22b-de05e0860eda.png)

**Comment by sehilyi** [comment]
@zhangzhen Thank you for finding this issue. It is indeed an unnecessary re-calculation.

Do you want to submit a PR for this as it looks you already made all necessary changes for vector data? I can make this change instead as well.

**Comment by zhangzhen** [comment]
> Do you want to submit a PR for this as it looks you already made all necessary changes for vector data?

I made this change on the master branch of my local repo without forking. It's better that you do it this time. Next time I will be glad to fork the repo and submit a PR for other changes.

Zhen

**Comment by sehilyi** [comment]
I opened a PR (#591), but it turns out to be that `clodius` actually adds up all nearby values instead of averaging it:

https://github.com/higlass/clodius/blob/e9883df34c5d1c4a9a121af75462b1a90abfc7b3/clodius/cli/aggregate.py#L160

That's the reason why values only increase as you zoom out (seeing wider region) in HiGlass tracks.

I think it would be good to expose aggregation functions to users so that users can select different functions (e.g., `sum`, `mean`, `count`, `min`, `max`).

**Comment by sehilyi** [comment]
Changed the title and tags since this is rather an enhancement that we can make.
