### ISSUE TITLE
Idea: Unify brush and rangeSelect mouse event

### ISSUE THREAD

**Issue by ThHarbig** [gosling-lang/gosling.js#910]
Right now there is a brush track as well as an experimental rangeSelect. While the brush track is used for linking views in gosling, the rangeSelect mouse event can be used to subscribe to range selections [outside of gosling](https://github.com/gosling-lang/gosling-react-example/blob/master/src/example/MouseEvents.jsx). 

Having a single brush for both purposes could make sense, but I am not sure how this fits in with the current logic. Let me know what you think and/or point me to the relevant sections of the code so I can have a go at it.

**Comment by sehilyi** [comment]
I like the idea of unifying the two. I think we need to think about whether we can better unify the (i) implementation and/or (ii) user API (`mark: 'brush'` vs. `"mouseEvents"`).

The brush in circular tracks is implemented [here](https://github.com/gosling-lang/gosling.js/blob/master/src/gosling-brush/brush-track.ts), and we are displaying linear brushes implemented in HiGlass (i.e., `viewport-projection-horizontal`), as can be found [here](https://github.com/gosling-lang/gosling.js/blob/67eb1bad45468975dc6b7113aec35a6d051d7976/src/core/higlass-model.ts#L144). We could re-implement the HiGlass' [viewport-projection-horizontal](https://github.com/higlass/higlass/blob/develop/app/scripts/ViewportTrackerHorizontal.js) in our repo if necessary.

I imagine we could implement a dedicated track for range selection or implement it in the current brush tracks.

**Comment by sehilyi** [comment]
The simplest solution would be to allow getting the selected window of the brush through an API (e.g., start and end positions) and then filter the shown data in the overlaid track through the `rawData` API.

**Comment by etowahadams** [comment]
I've been studying the implementation this morning and wanted to check my understanding:

As far as I can tell are three tracks that are used to draw brushes:   
- `brush-track`: One brush track is implemented in Gosling which is used for circular brushes. 
- `viewport-projection-horizontal`: This is a brush track implemented in HiGlass used to show brushes on linear tracks
- Gosling track with a `LinearBrushModel`. This is used for the mouseEvent `rangeSelect` and can be used to draw brushes on a gosling track. 

Here's where I could use some clarification: I'm still unclear as to what is going to replace what. Are you suggesting that rather than having a dedicated brush track (such as using `brush-track` or `viewport-projection-horizontal`), that Gosling track with LinearBrush model be used for all brushes? And for a linked view, you get the extent of the linear brush model, then filter the shown data using the rawDataAPI? Thanks for any clarification!

**Comment by sehilyi** [comment]
Thanks for exploring this issue already and bringing up these questions!

You are correct about the three implementations. Let's not think about unifying the three into one, which is a much bigger problem, and just stick to the simplest solution that works fine with gosling-meta use cases (https://github.com/gosling-lang/gosling.js/issues/910#issuecomment-1623861599 is what @ThHarbig and I decided during the yesterday meeting). So, you do not need to consider `LinearBrushModel` at this point.

The main idea would be to add an event type to the JS `subscribe` API:

https://github.com/gosling-lang/gosling.js/blob/afcf002654ee59fdbcada474458eacd56d264f71/src/core/gosling.schema.ts#L291-L298

The new event (say, 'location') should allow users to get the start and end positions of a track every time a user changes the genomic position (e.g., through zooming and panning).

```ts
// reference: https://github.com/gosling-lang/gosling.js/blob/afcf002654ee59fdbcada474458eacd56d264f71/src/core/pubsub.ts#L10-L15
gosRef.current.api.subscribe('location', (data) ⇒ {
   console.log(data); // data can contain id of a track and genomic location
});
```

(As a side note, we do not support subscribing to a specific track, so users will get a callback function for all tracks specified in the spec. This means users have to filter data by the ids of tracks of their interest on their own. This is not ideal if a user wants to subscribe to a single track and there are many tracks visualized. We might want to come up with a solution for supporting track-specific subscriptions).

The data that a user receives can be similar to what we have for `rangeSelect`:

https://github.com/gosling-lang/gosling.js/blob/afcf002654ee59fdbcada474458eacd56d264f71/src/core/gosling.schema.ts#L250-L254

I think this API can be just implemented in the gosling-track:

https://github.com/gosling-lang/gosling.js/blob/afcf002654ee59fdbcada474458eacd56d264f71/src/gosling-track/gosling-track.ts#L442-L456

Since the `zoomed` function is fired when the location changes, we can call the API function here, something like:

```ts
publish('location', {
    id: context.viewUid,
    genomicPosition,
    ...
});
```

Since a brush track (either `brush-track` or `viewport-projection-horizontal`) is always linked to a track, users can get the start and end position of a brush by referring to the id of a track that is linked with the brush when using the `location` function.

Example Spec:
```ts
views: [
   { ..., tracks: [..., { type: 'brush', x: { linkingId: 'detail' } }]},
   { tracks: [{ ..., id: 'detail-track-1', x: { ..., linkingId: 'detail' } }]
]
```

Example API:
```ts
gosRef.current.api.subscribe('location', (data) ⇒ {
  const { id, genomicPosition } = data;
  if(id === 'detail-track-1') {
      console.log('brush has been moved to ', genomicPosition);
   }
});
```

**Comment by sehilyi** [comment]
@ThHarbig can you confirm if [the approach I described above](https://github.com/gosling-lang/gosling.js/issues/910#issuecomment-1625623218) fulfills your use cases?

**Comment by ThHarbig** [comment]
yes, sounds perfect!

**Comment by etowahadams** [comment]
I got a working implementation this morning and have testing it! Thanks for all the implementation tips, Sehi. 

What do you want the behavior to be when the range precedes the start or end of the chromosomes?  Currently it gives a position on an "unknown" chromosome". For example, here is a genomic axis which includes all of the chromosomes. 
```
[
  { chromosome: "unknown", position: -571673.1831731489 },
  { chromosome: "unknown", position: 26441823.0193935344 }
]
```
I'm trying to think of use cases when the subscriber would want to know how much of the "unknown" region is being viewed but I can't think of any off the top of my head. Would you like it to return the minimum chromosome position (chr1, 0) and the maximum chromosome position instead?

**Comment by sehilyi** [comment]
I think min and max chromosome positions make more sense since those genomic positions (e.g., negative positions) do not actually exist. Users would be confused when they see such values and I cannot think of any use cases using such values as well.
