### ISSUE TITLE
onNewView/onNewTrack functionality

### ISSUE THREAD

**Issue by ThHarbig** [gosling-lang/gosling.js#926]
Create an event that is dispatched when a new view/track has been created to get the data and other information/e.g. dimensions, specification etc. about the track/view.

See also view API of vega: https://vega.github.io/vega/docs/api/view/

**Comment by sehilyi** [comment]
It could be something like the following:
```
api.subscribe('onNewTrack', 'track-1', () ⇒ {})
```

The data received from the callback function should be dimensions (only rectangular shape, i.e., widht height, x, y), data, and spec.

**Comment by etowahadams** [comment]
Should you be able to subscribe to tracks belonging to a particular view? Or should the subscription just give you give you all track additions?  
```
// subscriptions to a specific view
api.subscribe('onNewView', 'myViewName', () ⇒ {})

// subscribe to all tracks added 
api.subscribe('onNewView', () ⇒ {})

```

Here's my sketch of what the data returned will look like. 

```
interface CommonEventData {
    /** Source visualization ID, i.e., `track.id` */
    id: string;
    /** Values in a JSON array that represent data after data transformation */
    data: Datum[];
}

interface OnNewViewEventData extends CommonEventData {
    /** Expanded track specification processed by the Gosling compiler, e.g., default properties filled in. */
    spec: SingleTrack | OverlaidTrack;

    /** The shape of the source track */
    shape: LinearTrackShape | CircularTrackShape;
}
```

**Comment by sehilyi** [comment]
To provide clarifications first (since I found my previous explanation too brief), we want to enable users to get the information of a track or a view, and we want to enable that by supporting `onNewTrack` and `onNewView` APIs, respectively (feel free to name differently that are more intuitive!).

- `onNewTrack` should allow users to get the information of a track (e.g., bounding box of a track)
- `onNewView` should allow users to get the information of a view (e.g., bounding box of a view that contains one or multiple tracks)

The first API will be easier to implement. We can publish the event in the `gosling-track.ts` when the track has been rendered for the first time, e.g., https://github.com/gosling-lang/gosling.js/blob/9eb7a7bf458c2862996b5c558f1f93a7e74066f6/src/gosling-track/gosling-track.ts#L296

The second API is more complicated since we (1) need to know which tracks belong to a specific view, and (2) we need to calculate the bounding box of the view by referring to the bounding boxes of tracks in the corresponding view.

Regarding your question, I think either works for our use cases. If you can come up with a solution to subscribe to a track (for `onNewTrack`) and a view (for `onNewView`). I think this is ideal since we do not need to send large `data` objects for tracks that are not of users' interest.

**Comment by etowahadams** [comment]
I've been trying to figure out how I'm going to implement `onNewView` by scouring through the code base. I'd like to check my understanding thus far: 

- Each gosling track model is unaware of the view that it belongs to. Therefore, we have to figure out if a new view has been added by looking at the `GoslingSpec`. 
- The size of each track is calculated in `traverseAndCollectTrackInfo` which is recursive process. 
https://github.com/gosling-lang/gosling.js/blob/c00671aa84a0cff82a06ee72b53222156590995e/src/core/utils/bounding-box.ts#L151
- `traverseToFixSpecDownstream` associates `linkingId`of the parent to the child. 

## Proposed implementation: 
We need a way to know if track is associated with a particular view. To do that, every view needs to have a unique ID. 

Therefore, I propose that we autogenerate a unique ID for each view. The `viewId` will be inherited by child tracks in `traverseToFixSpecDownstream`. However, it is possible to have nested views, so some tracks will have multiple `viewId`s. 

Since every track is now associated with a view, I should be able to iterate through `trackInfos` in the `compile` function to figure out the size of every view. 

https://github.com/gosling-lang/gosling.js/blob/c00671aa84a0cff82a06ee72b53222156590995e/src/core/compile.ts#L34-L37

There's one part I haven't quite figured out yet. When the spec gets updated, I assume `compile` is called again (correct me if I'm wrong!). I need to know the `viewIds` from the previous GoslingSpec, but at this point, its not clear to me where I would have that information persist. Perhaps in `HiGlassModel`? I still need to figure out if every time the spec is edited, `renderHiGlass` is called and a new HiGlassModel is created or not. 

Does this sound like more or less what you would do?

**Comment by etowahadams** [comment]
I've implemented a barebones version in this commit https://github.com/gosling-lang/gosling.js/pull/940/commits/d7c10138cca27785dcf49567c9a336d1f5d64fe5. I can now trigger an event when a new view is added. I've been testing it with this gist by deleting views and adding them back.  

http://localhost:3000/?gist=etowahadams/83ee916823cea9ac0698352ec2c6fcba

The strategy is to have an ID associated with each view. The `viewId` can be set by the user, and otherwise they are autogenerated. The tracks within a view inherit the `viewId`. 
- I still need to cover the case for nested views, where a track should have multiple `viewId`s associated with them. 
- Auto-generated `viewId`s are not persistent between re-compiles. Still need to figure out how to make them persistent if we would want to support `onNewView` events where the view does not have a user specified `viewId`.  

Since each track is now associated with a `viewId` in the `TrackInfo`, I can compare the previous trackInfos with the current trackInfos to figure out whether a new view has been added or not. I do this inside of `GoslingComponent.` 
- I still need to figure out how to calculate the bounding boxes of each view. I think this should be possible using `getBoundingBox`

## Questions to be addressed
- How do we feel about having a `viewId` that users can specify for each view? Example: 
```
"views": [
  {
    "viewId": "view-1",
     ...
```
- Should a user specified `viewId` be required for `onNewView` to be triggered? If no then I will have to figure out a way to do diffs on new vs old gosling schemas to automatically figure out which views are new or old. 
- Is the strategy I'm currently pursuing where I compare the previous `trackInfos` with new `trackInfos` to figure out the new view the most appropriate method?

**Comment by sehilyi** [comment]
Let's discuss these during the meeting today! It looks like we now see an overlap between this effort and my work on supporting view IDs (https://github.com/gosling-lang/gosling.js/issues/929).

**Comment by etowahadams** [comment]
Sounds good!
